### ISSUE TITLE
The script fails if the account has multiple subscription IDs associated

### ISSUE THREAD

**Issue by tulikac** [logicappsio/LogicAppConnectionAuth#1]
if you do a 
$subscription = Get-AzureRmSubscription -SubscriptionId $subscriptionId 

after the login, no matter what you specify, it will take the default subscription ID associated with the account, ignoring the parameter which has been passed.

You can workaround that problem by using
$subscription = Select-AzureRmSubscription -SubscriptionId $subscriptionId

**Comment by jeffhollan** [comment]
Thanks for reporting (and listing the fix) - just patched it in commit #9c6941d
